name: akismet
version: 4.0.0

author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using the Akismet service. Add Akismet to your applications so you don't have to worry about spam again.
documentation: https://dev.belin.io/akismet.dart/api
homepage: https://dev.belin.io/akismet.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3
  json_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^0.10.2
  build_version: ^1.0.0
  coverage: ^0.12.2
  coveralls: ^4.0.0
  grinder: ^0.8.3
  json_serializable: ^1.2.1
  test: ^1.3.0
