name: akismet
version: 1.0.0

author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using Akismet service.
documentation: https://cedx.github.io/akismet.dart
homepage: https://github.com/cedx/akismet.dart

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  args: ^0.13.7
  path: ^1.4.1

dev_dependencies:
  coverage: ^0.8.0
  test: ^0.12.17
