name: akismet
version: 4.0.0

author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using the Akismet service. Add Akismet to your applications so you don't have to worry about spam again.
documentation: https://dev.belin.io/akismet.dart/api
homepage: https://dev.belin.io/akismet.dart
issue_tracker: https://github.com/cedx/akismet.dart/issues
repository: https://github.com/cedx/akismet.dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.9
  build_version: ^2.0.1
  code_builder: ^3.2.0
  grinder: ^0.8.3
  grinder_coveralls: ^2.0.0
  json_serializable: ^3.2.3
  test: ^1.9.3
