name: akismet
version: 4.1.0

description: >
  Prevent comment spam using the Akismet service.
  Add Akismet to your applications so you don't have to worry about spam again.
homepage: https://docs.belin.io/akismet.dart
issue_tracker: https://git.belin.io/cedx/akismet.dart/issues
repository: https://git.belin.io/cedx/akismet.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http: ^0.12.1
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.2.0
  build_version: ^2.0.1
  coverage: ^0.14.0
  coveralls: ^5.9.0
  json_serializable: ^3.3.0
  test: ^1.15.2
