name: akismet
version: 4.0.0

author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using the Akismet service. Add Akismet to your applications so you don't have to worry about spam again.
documentation: https://dev.belin.io/akismet.dart/api
homepage: https://dev.belin.io/akismet.dart
issue_tracker: https://github.com/cedx/akismet.dart/issues
repository: https://github.com/cedx/akismet.dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.2.7
  build_test: ^0.10.6
  build_version: ^2.0.0
  build_web_compilers: ^1.1.0
  coverage: ^0.12.4
  coveralls: ^5.1.0
  grinder: ^0.8.3
  json_serializable: ^2.0.2
  test: ^1.5.3
