name: akismet
version: 3.0.0

author: Cédric Belin <cedric@belin.io>
description: Prevent comment spam using the Akismet service.
documentation: https://cedx.github.io/akismet.dart
homepage: https://github.com/cedx/akismet.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  http: ^0.11.3

dev_dependencies:
  coverage: ^0.9.3
  coveralls: ^2.0.1
  grinder: ^0.8.0
  test: ^0.12.27

transformers:
- test/pub_serve:
    $include: test/**.dart
